spring:
  application:
    name:
      HotelOnlineReservationSystem
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://localhost:3306/hors
    username: hors
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  error:
    include-message:
      always